// Generated by CoffeeScript 1.3.3
(function() {
  var Client, Player, app, express, io, players, server;

  express = require('express');

  app = express();

  Client = require('./public/js/client.js');

  Player = Client.Player;

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/public/index.html');
  });

  app.configure(function() {
    app.use(express["static"](__dirname + '/public'));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  players = [];

  server.listen(6543);

  io.sockets.on('connection', function(socket) {
    var newPlayer;
    socket.emit('init', {
      players: players
    });
    newPlayer = new Player((Math.random() * 500) + 1, (Math.random() * 500) + 1, 1, 'woodne');
    io.sockets.emit('add', {
      player: newPlayer
    });
    return players.push(newPlayer);
  });

}).call(this);
